name: Maven Build and Dependabot Scan

on:
  push:
    branches:
      - main

jobs:
  maven_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

  dependabot:
    needs: maven_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependabot
        uses: dependabot/dependabot-action@v2
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}

      - name: Dependabot Alert CSV Export
        uses: ShamKarthikS-Hexaware/dependabot-alert-export@v1.0
        with:        
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          org_name: 'DevSecOps-20'
          repo_name: 'nodejs.org'
          csv_path: data/vulnerability.csv

      - name: Upload Vulnerability report
        uses: actions/upload-artifact@v3
        with:
           name: vulnerability_report
           path: data/vulnerability.csv
